'use strict';

angular
	.module('services.config',[])
	.constant('configuration', {
		//common environment configuration
		rheticusHeaderImage : "./images/RheticusLogo.png",
		timeSlider : {"domain":{"start":"2014-10-01T00:00:00Z","end":""},"brush":{"start":"2014-10-01T00:00:00Z","end":""},"attributes":{"CQL_FILTER":{"startDate":"startTime","endDate":"stopTime"},"datasetIdentifier":"datasetId"}},
		filters : {"speedSlider":{"init":"0;20","from":0,"to":20,"step":0.5,"dimension":"mm/year","scale":[0,"|",5,"|",10,"|",15,"|",20]},"coherenceSlider":{"_comment":"NOT YET IMPLEMENTED","init":"75;100","from":75,"to":100,"step":0.5,"dimension":"%","scale":[75,"|",90,"|",100]}},
		map : {"center":{"lon":15.85,"lat":38.325,"zoom":14},"query":{"zoom":16},"crs":"EPSG:3857"},
		aoi : [{"name":" Barritteri","bbox":{},"selected":true},{"name":" Trento","bbox":{},"selected":false}],
		//custom environment configuration
		layers : {"baselayers":[{"name":"OpenStreetMap","group":"base","source":{"type":"OSM"},"active":false,"opacity":1},{"name":"Ortofoto RealVista 1.0","group":"base","source":{"type":"TileWMS","urls":["http://kim.planetek.it:9080/geoserver/rheticus/gwc/service/wms"],"params":{"LAYERS":"rheticus:rv1","TILED":true},"serverType":"geoserver"},"active":true,"opacity":1}],"overlays":{"olLayers":[{"id":"iffi","name":"Aree a rischio frana","group":"Overlays","source":{"type":"TileWMS","urls":["http://kim.planetek.it:9080/geoserver/rheticus/gwc/service/wms"],"params":{"LAYERS":"rheticus:97,rheticus:98,rheticus:99","TILED":true},"serverType":"geoserver"},"active":false,"opacity":0.8},{"id":"sentinel","name":"Sentinel 1 Datasets GeoJSON","group":"Overlays","source":{"type":"GeoJSON","url":"./stub/geojson.json"},"active":false,"opacity":0.8},{"id":"ps","name":"Persistent Scatterers Map","group":"Overlays","source":{"type":"TileWMS","urls":["http://kim.planetek.it:9080/geoserver/rheticus/gwc/service/wms"],"params":{"LAYERS":"rheticus:ps_barritteri_heatmap","TILED":true},"serverType":"geoserver"},"active":true,"opacity":0.8}],"metadata":[{"id":"iffi","type":"","queryUrl":"","legend":{"name":"Landslide Maps","title":"Here you will control the visualization of landslide maps covering the area (IFFI catalog).Single-clicking a point in the landslide enables the access to the features of the landlside.","uom":"","url":{"tipologia_frana":"./images/Frane.png","area_frane_diffuse":"./images/Aree_frane_diffuse.png","piff":"./images/Punto_identificativo_frana.png"}},"custom":{}},{"id":"sentinel","type":"ImageWMS","queryUrl":"http://kim.planetek.it:9080/geoserver/rheticus/wms","legend":{"name":"Sentinel Catalog","title":"Here you will query the whole Sentinel-1 (S1) catalog by single-clicking a point on the map.Then you will check the S1 population and dataset identification for PS processing. ","uom":"","url":{"nothing":""}},"custom":{"LAYERS":"rheticus:slc"}},{"id":"ps","type":"RheticusApiRest","queryUrl":"http://kim.planetek.it:8081/api/v1/datasets/datasetid/pss/psid/measures?type=DL","legend":{"name":"Displacement Maps","title":"Here you will find the list of displacement maps covering the area.Choose your map and single-click each point of the map to enable the access to the measurements. ","uom":"[mm/year]","url":{"velocity":"./images/legend_vel_ps.png"}},"custom":{"heatmap":"rheticus:ps_barritteri_heatmap","detail":"rheticus:ps","datasetid":"datasetid","psid":"psid","date":"data","measure":"measure"}}]}}
	});
