'use strict';

angular
	
	.module('services.config', [])
	
	.constant('configuration', {
		//common environment configuration
		rheticusHeaderTitle : 'Rheticus™',
		timeSlider : {"domain":{"start":"2014-01-01T00:00:00Z","end":"2016-01-01T00:00:00Z"},"brush":{"start":"2015-01-10T00:00:00Z","end":"2015-06-10T00:00:00Z"}},
		filters : {"speedSlider":{"init":"0;20","from":0,"to":20,"step":0.5,"dimension":"mm/year","scale":[0,"|",5,"|",10,"|",15,"|",20]},"coherenceSlider":{"_comment":"NOT YET IMPLEMENTED","init":"75;100","from":75,"to":100,"step":0.5,"dimension":"%","scale":[75,"|",90,"|",100]}},
		datasets : [{"name":"dataset1","selected":true},{"name":"dataset2","selected":true},{"name":"dataset3","selected":true}],
		//custom environment configuration
		legends : {"_comment":"Barritteri legend style","velocity":{"title":"Velocità PS ","uom":"[mm/period]","url":"http://morgana.planetek.it:8080/geoserver/pkt284/wms?REQUEST=GetLegendGraphic&VERSION=1.3.0&FORMAT=image/png&WIDTH=20&HEIGHT=20&LAYER=pkt284:ps_barritteri_raster_vel&TRANSPARENT=true&LEGEND_OPTIONS=fontColor:0xffffff;fontAntiAliasing:true"},"density":{"title":"Densità PS ","uom":"[ps/100㎡]","url":"http://morgana.planetek.it:8080/geoserver/pkt284/wms?REQUEST=GetLegendGraphic&VERSION=1.3.0&FORMAT=image/png&WIDTH=20&HEIGHT=20&LAYER=pkt284:ps_barritteri_raster&TRANSPARENT=true&LEGEND_OPTIONS=fontColor:0xffffff;fontAntiAliasing:true"},"ps":{"title":"Velocità PS ","uom":"[mm/period]","url":"http://morgana.planetek.it:8080/geoserver/pkt284/wms?REQUEST=GetLegendGraphic&VERSION=1.3.0&FORMAT=image/png&WIDTH=20&HEIGHT=20&LAYER=pkt284:ps_barritteri_view&TRANSPARENT=true&LEGEND_OPTIONS=fontColor:0xffffff;fontAntiAliasing:true&STYLE=pkt284:ps_legend_style"}},
		maps : {"center":{"lon":15.85,"lat":38.325},"zoom":{"center":14,"detail":17},"baselayers":[{"name":"e-Geos Ortofoto RealVista 1.0","id":"rv1","visible":true,"opacity":1,"source":{"isBaseLayer":true,"type":"TileWMS","urls":["http://morgana.planetek.it:8080/geoserver/gwc/service/wms"],"params":{"LAYERS":"pkt284:rv1","VERSION":"1.3.0","SRS":"EPSG:3857","TILED":true}}}],"overlays":{"barritteri":{"heatmap":{"name":"Barritteri Heat Map","id":"ps_barritteri_raster","visible":true,"opacity":0.8,"source":{"type":"TileWMS","urls":["http://morgana.planetek.it:8080/geoserver/gwc/service/wms"],"minScale":10000,"params":{"LAYERS":"pkt284:ps_barritteri_raster","VERSION":"1.3.0","SRS":"EPSG:3857","TILED":true},"serverType":"geoserver"}},"view":{"name":"Barritteri Persistent Scatterers Map","id":"ps_barritteri_view","visible":true,"opacity":0.8,"source":{"type":"TileWMS","urls":["http://morgana.planetek.it:8080/geoserver/gwc/service/wms"],"maxScale":10000,"params":{"LAYERS":"pkt284:ps_barritteri_view","VERSION":"1.3.0","SRS":"EPSG:3857","TILED":true},"serverType":"geoserver"}},"query":{"name":"Barritteri Persistent Scatterers Map Query","id":"ps_barritteri","visible":false,"source":{"type":"TileWMS","urls":["http://morgana.planetek.it:8080/geoserver/pkt284/wms"],"params":{"LAYERS":"pkt284:ps_barritteri","VERSION":"1.3.0"},"serverType":"geoserver"}}},"trento":{"heatmap":{"name":"Trento Heat Map","id":"PS_heatmap_100m","visible":true,"opacity":0.8,"source":{"type":"TileWMS","urls":["http://morgana.planetek.it:8080/geoserver/gwc/service/wms"],"minScale":10000,"params":{"LAYERS":"pkt284:PS_heatmap_100m","VERSION":"1.3.0","SRS":"EPSG:3857","TILED":true},"serverType":"geoserver"}},"view":{"name":"Trento Persistent Scatterers Map","id":"ps_trento_view","visible":true,"opacity":0.8,"source":{"type":"TileWMS","urls":["http://morgana.planetek.it:8080/geoserver/gwc/service/wms"],"maxScale":10000,"params":{"LAYERS":"pkt284:ps_trento_view","VERSION":"1.3.0","SRS":"EPSG:3857","TILED":true},"serverType":"geoserver"}},"query":{"name":"Trento Persistent Scatterers Map Query","id":"ps_trento","visible":false,"source":{"type":"TileWMS","urls":["http://morgana.planetek.it:8080/geoserver/pkt284/wms"],"params":{"LAYERS":"ps_trento","VERSION":"1.3.0"},"serverType":"geoserver"}}},"sentinel":{"view":{"name":"Sentinel 1 Datasets","id":"dati_sentinel","visible":false,"source":{"type":"TileWMS","urls":["http://kim.planetek.it:9080/geoserver/rheticus/wms"],"params":{"LAYERS":"rheticus:dati_sentinel","VERSION":"1.3.0","SRS":"EPSG:3857","TILED":true},"serverType":"geoserver"}},"query":{"name":"Sentinel 1 Datasets Query","id":"dati_sentinel_geojson","visible":false,"source":{"type":"GeoJSON","url":"jsonData/FeatureCollection.json"}}}}}
	});
