#! /bin/bash
 
### BEGIN INIT INFO
# Provides:          logstash
# Required-Start:    $network $remote_fs $named $elasticsearch
# Required-Stop:     $network $remote_fs $named $elasticsearch
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start logstash at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO
 
. /lib/lsb/init-functions

name="Logstash"
exec_bin="/opt/logstash-*/bin/logstash"
logstash_conf="/opt/logstash-*/bin/logstash.conf"
logstash_log="/var/log/logstash.log"
pid_file="/var/run/logstash.pid"
command_opts="-f ${logstash_conf} -l ${logstash_log}"

start () {
        log_daemon_msg "Starting $name"
        if start-stop-daemon --quiet --oknodo --pidfile "$pid_file" -b -m --exec $exec_bin --start -- $command_opts; then
                log_end_msg 0
        else
                log_end_msg 1
        fi
}
 
stop () {
        log_daemon_msg "Stopping $name"
        start-stop-daemon --stop --oknodo --pidfile "$pid_file" --retry=TERM/20/KILL/5
}

status () {
        status_of_proc -p $pid_file $exec_bin "$name"
        scode="$?"
        if [ $scode -eq 0 ]; then log_action_msg "Process id: $(cat $pid_file)"; fi
        return $scode
}

case $1 in
        start)
                if status; then exit 0; fi
                start
                ;;
        stop)
                stop
                ;;
        reload)
                stop
                start
                ;;
        restart)
                stop
                start
                ;;
        status)
                status && exit 0 || exit $?
                ;;
        *)
                echo "Usage: $0 {start|stop|restart|reload|status}"
                exit 1
                ;;
esac
exit 0
