#! /bin/bash
 
### BEGIN INIT INFO
# Provides:          mule
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start mule at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO
 
. /lib/lsb/init-functions

name="Mule"
exec_bin="/opt/mule-standalone-*/bin/mule"

USAGE="Usage: $0 {\e[00;32mstart\e[00m|\e[00;31mstop\e[00m|\e[00;32mstatus\e[00m|\e[00;31mrestart\e[00m}"


case $1 in
        start)
                $exec_bin start
                ;;
        stop)
                $exec_bin stop
                ;;
        reload)
                $exec_bin restart
                ;;
        restart)
                $exec_bin restart
                ;;
        status)
                $exec_bin status
                ;;
        *)
                echo -e $USAGE
                exit 1
                ;;
esac
exit 0
